### ISSUE TITLE
Ability to post images (and perhaps videos)

### ISSUE THREAD

**Issue by Piedone** [nearform-actions/github-action-notify-twitter#642]
This action looks great to post text tweets, but it doesn't seem to support adding images or videos. It would be great to support that too (note that images also need descriptions, i.e. `alt` attributes).

**Comment by simoneb** [comment]
Are you interested in sending a PR for this?

**Comment by Piedone** [comment]
Thanks for your quick reply! Sadly JS is really out of my expertise, so I won't be able to.

**Comment by AlessioScarfone** [comment]
Hi @Piedone, I submitted a PR (#656 ) to include support for multimedia elements in this action. Could you please review it? Thanks.

**Comment by Piedone** [comment]
I can only check it as a user, but as such, it looks good, thank you!
